# Generated by Django 3.1.1 on 2020-10-10 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostView',
        ),
    ]
